version: '3.1'
services:
  stats-server:
    build: ewm-stat/
    image: 'ewm-stat'
    container_name: explore_with_me_stat_container
    ports:
      - "9090:9090"
    depends_on:
    - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stat

  stats-db:
    image: postgres:14-alpine
    container_name: explore_with_me_stat_db
    ports:
        - "6543:5432"
    volumes:
        - /var/lib/postgresql/data/
    environment:
        - POSTGRES_DB=ewm-stat
        - POSTGRES_USER=Explorer
        - POSTGRES_PASSWORD=Explorer

  ewm-service:
    build: ewm-main/
    image: 'ewm-main'
    container_name: explore_with_me_main_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - ewm-stat.url=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore-with-me

  ewm-db:
    image: postgres:14-alpine
    container_name: explore_with_me_main_db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=explore-with-me
      - POSTGRES_USER=Explorer
      - POSTGRES_PASSWORD=Explorer
